server:
  port: 8100
spring:
  application:
    name: springboot-easyexcel
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


filepath: D:\easyexcel
